### ISSUE TITLE
Use i18n key for table headers

### ISSUE THREAD

**Issue by mattr** [katalyst/katalyst-tables#4]
The builder currently uses `param_key` to provide `object_name` used for label lookup. For a lookup in the locale file, however, it would make more sense to use the `i18n_key` entry for consistent referencing. (Note that this only makes a difference for namespaced models which use `/` to delineate namespaces in locales but `_` in params.)

Example:
```ruby
class ParentItem
  class Inner
  end
end

ParentItem::Inner.model_name.param_key # => parent_item_inner
ParentItem::Inner.model_name.i18n_key # => parent_item/inner
```

If we need to apply form wrapping on the table, it may be necessary to provide both options from the collection.

**Comment by sfnelson** [comment]
Hey @mattr – my goal was to make this as easy-to-use as possible, ideally working out of the box without any user input. I think `i18n_key` is more appropriate, happy to accept a PR for this change.
